$(document).ready(function(){
	$('a#en').click(function(event){
		$('.fr').slideUp("slow");
		$('.en').slideDown("slow");
		event.preventDefault();
	});
	$('a#fr').click(function(event){
		$('.en').slideUp("slow");
		$('.fr').slideDown("slow");
		event.preventDefault();
	});
});